import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, relative, resolve } from "node:path";
import { defineCommand } from "citty";
import pc from "picocolors";
import { pickProject } from "../utils/prompts.js";

/** Recursively yields all .md/.mdx files under a directory. */
function* walkDocs(dir: string): Generator<string> {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      yield* walkDocs(full);
    } else if (/\.mdx?$/i.test(entry.name)) {
      yield full;
    }
  }
}

/** Best-effort title: frontmatter `title:`, then first H1, then filename. */
function extractTitle(file: string): string {
  const text = readFileSync(file, "utf8");
  const frontmatter = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  const fmTitle = frontmatter?.[1].match(/^title:\s*["']?(.+?)["']?\s*$/m)?.[1];
  if (fmTitle) return fmTitle;
  const h1 = text.match(/^#\s+(.+)$/m)?.[1];
  if (h1) return h1;
  return basename(file).replace(/\.mdx?$/i, "");
}

export default defineCommand({
  meta: {
    name: "generate",
    description: "Generate an llms.txt index of a project's docs",
  },
  args: {
    name: {
      type: "positional",
      description: "Project name (prompted when omitted)",
      required: false,
    },
    out: {
      type: "string",
      alias: "o",
      description: "Output file (defaults to <docs folder>/llms.txt)",
    },
  },
  async run({ args }) {
    const project = await pickProject(args.name);

    const docsPath = join(project.path, "docs");
    if (!existsSync(project.path)) {
      console.error(
        pc.red(`mdxctl folder for "${project.name}" no longer exists: ${project.path}`),
      );
      process.exit(1);
    }
    if (!existsSync(docsPath)) {
      console.error(
        pc.red(`Docs subfolder for "${project.name}" no longer exists: ${docsPath}`),
      );
      process.exit(1);
    }

    const files = [...walkDocs(docsPath)].sort();
    if (files.length === 0) {
      console.error(pc.yellow(`No .md/.mdx files found under ${docsPath}`));
      process.exit(1);
    }

    const lines = files.map((file) => {
      const rel = relative(docsPath, file).split("\\").join("/");
      return `- [${extractTitle(file)}](${rel})`;
    });

    const content = [
      `# ${project.name}`,
      "",
      `> Documentation index for ${project.name}, generated by mdxctl.`,
      "",
      "## Docs",
      "",
      ...lines,
      "",
    ].join("\n");

    const outPath = args.out
      ? resolve(args.out)
      : join(docsPath, "llms.txt");
    writeFileSync(outPath, content, "utf8");

    console.log(
      pc.green("✓") +
        ` Wrote ${pc.dim(outPath)} (${files.length} doc${files.length === 1 ? "" : "s"})`,
    );
  },
});
