import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { VERSION } from "./version.js";

/**
 * Generates editor support for the .mdx files inside a user's mdxctl folder.
 *
 * The problem: docs live in an arbitrary folder on the user's machine, usually
 * a repo that has never heard of Astro or TypeScript. Opening
 * `<project>/.mdxctl/docs/index.mdx` there gives no autocomplete and a red
 * squiggle on every component import, even though the file renders perfectly
 * once `mdxctl start` links it into the docs app.
 *
 * The fix is two generated files next to the docs:
 *
 *   .mdxctl/tsconfig.json     — scopes the language server to this folder
 *   .mdxctl/mdxctl-env.d.ts   — declares the components and their props
 *
 * Both are intentionally self-contained: no `astro` import, no path mapping
 * into the mdxctl install (which lives in a version-stamped directory that
 * moves on every upgrade). The declarations are structural, so they type-check
 * in a folder with zero node_modules.
 *
 * Rewritten on every `init` and every `start` so the props never drift from the
 * installed version.
 */

/** Marker line so we can recognise (and safely overwrite) our own output. */
const GENERATED_MARKER = "@generated by mdxctl";

function header(kind: "ts" | "json"): string {
  const lines = [
    `${GENERATED_MARKER} v${VERSION} — do not edit.`,
    "",
    "Regenerated by `mdxctl init` and every `mdxctl start`, so any manual",
    "change here is lost on the next run. Safe to commit or to gitignore;",
    "mdxctl recreates it either way.",
  ];
  if (kind === "json") {
    return `// ${lines.join("\n// ")}\n`;
  }
  return `/**\n * ${lines.join("\n * ")}\n */\n`;
}

/**
 * The component surface available to .mdx docs.
 *
 * Props are duplicated from the .astro components by hand rather than derived,
 * because the docs-app is not resolvable from the user's folder. Keep in sync
 * with packages/docs-app/src/components/.
 */
const COMPONENT_TYPES = `
/** Props accepted by the CodeBlock component. */
interface MdxctlCodeBlockProps {
  /**
   * The code to render. Only needed when the code is computed; a plain
   * \`\`\`ts fence is usually the better choice and needs no import.
   */
  code?: string;
  /** Language id, e.g. "ts", "bash", "json". See https://shiki.style/languages */
  lang?: string;
  /** Filename shown in the header bar, e.g. "src/cli.ts". */
  title?: string;
  /** Lines to highlight, e.g. "2" or "2,4-6". */
  highlight?: string;
  /** Soft-wrap long lines instead of scrolling horizontally. */
  wrap?: boolean;
  class?: string;
}

/** Props accepted by the Callout component. */
interface MdxctlCalloutProps {
  type?: "info" | "success" | "warning" | "error";
}
`.trim();

/**
 * Module declarations backing the "@mdxctl/..." alias used by explicit imports.
 *
 * There is deliberately no `MDXProvidedComponents` declaration here. mdxctl
 * injects exactly one thing at render time — a `pre` element override that
 * upgrades fenced code blocks — and no named components. Declaring CodeBlock
 * or Callout as provided globals would tell the editor that `<Callout>` works
 * without an import, and it would then fail at render as an undefined
 * component. Every component must be imported.
 */
const AMBIENT_DECLARATIONS = `
/**
 * Imports resolve through the "@mdxctl/..." alias, which the docs app maps to
 * its bundled component library at render time:
 *
 *     import Callout from "@mdxctl/Callout.astro";
 *
 * The modules are declared rather than resolved, since the real files live
 * inside the mdxctl install rather than in this folder.
 */
declare module "@mdxctl/CodeBlock.astro" {
  const CodeBlock: (props: MdxctlCodeBlockProps) => unknown;
  export default CodeBlock;
}

declare module "@mdxctl/Callout.astro" {
  const Callout: (props: MdxctlCalloutProps) => unknown;
  export default Callout;
}

export {};
`.trim();

function envDts(): string {
  return `${header("ts")}\n${COMPONENT_TYPES}\n\n${AMBIENT_DECLARATIONS}\n`;
}

function tsconfig(): string {
  const config = {
    compilerOptions: {
      // No emit and no lib checks: this config exists purely so the editor's
      // language server picks up mdxctl-env.d.ts for the .mdx files here.
      target: "ESNext",
      module: "ESNext",
      moduleResolution: "bundler",
      noEmit: true,
      skipLibCheck: true,
      allowJs: true,
      strict: true,
      jsx: "preserve",
      types: [],
    },
    include: ["mdxctl-env.d.ts", "**/*.mdx"],
  };
  return `${header("json")}${JSON.stringify(config, null, 2)}\n`;
}

/**
 * True when a file is absent or was produced by us. Guards against clobbering
 * a tsconfig.json the user wrote themselves — plausible if their docs folder
 * doubles as something else.
 */
function safeToWrite(path: string): boolean {
  if (!existsSync(path)) return true;
  try {
    return readFileSync(path, "utf8").includes(GENERATED_MARKER);
  } catch {
    return false;
  }
}

export interface DocsTypesResult {
  /** Files actually written this run. */
  written: string[];
  /** Files skipped because the user appears to own them. */
  skipped: string[];
}

/**
 * Writes the generated editor-support files into an mdxctl folder.
 *
 * Never throws: typegen is a convenience, and a read-only folder or an
 * exotic filesystem should not take down `init` or `start`.
 */
export function writeDocsTypes(mdxctlPath: string): DocsTypesResult {
  const result: DocsTypesResult = { written: [], skipped: [] };

  const targets: Array<{ path: string; content: string }> = [
    { path: join(mdxctlPath, "mdxctl-env.d.ts"), content: envDts() },
    { path: join(mdxctlPath, "tsconfig.json"), content: tsconfig() },
  ];

  try {
    mkdirSync(mdxctlPath, { recursive: true });
  } catch {
    return result;
  }

  for (const target of targets) {
    if (!safeToWrite(target.path)) {
      result.skipped.push(target.path);
      continue;
    }
    try {
      // Skip identical content so `start` does not churn mtimes (and file
      // watchers) on every run.
      if (existsSync(target.path)) {
        if (readFileSync(target.path, "utf8") === target.content) continue;
      }
      writeFileSync(target.path, target.content, "utf8");
      result.written.push(target.path);
    } catch {
      // Best effort — docs still render without editor support.
    }
  }

  return result;
}
