/**
 * Workaround for a Node regression that kills the portless proxy.
 *
 * Node ships an HTTP/1 fallback inside `http2.createSecureServer({
 * allowHTTP1: true })` — the mode portless uses to serve one TLS port for both
 * protocols. In Node 22.21.0 the HTTP/1 connection listener started calling
 * `server.shouldUpgradeCallback(req)` for any request carrying an `Upgrade`
 * header, but that method is only installed on `http.Server` instances, not on
 * HTTP/2 servers. The first WebSocket handshake therefore throws
 *
 *   TypeError: server.shouldUpgradeCallback is not a function
 *       at parserOnIncoming (node:_http_server)
 *
 * inside the daemon, which exits. In mdxctl the trigger is Vite's HMR socket:
 * the first page renders fine, then the proxy is gone and every later
 * navigation fails with ERR_CONNECTION_REFUSED — including the docs URLs the
 * status card just printed.
 *
 * The shim below restores the missing method with Node's own semantics
 * (`listenerCount("upgrade") > 0`), so portless receives the `upgrade` event it
 * already handles and proxies HMR properly. It is injected into the daemon with
 * `NODE_OPTIONS=--require`, and installs nothing on Node versions that either
 * predate the call or ship the method themselves.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createSecureServer } from "node:http2";
import { createServer } from "node:http";
import { join } from "node:path";
import { REGISTRY_DIR } from "../registry.js";

const SHIM_FILENAME = "node-http2-upgrade-shim.cjs";

const SHIM_SOURCE = `// Generated by mdxctl — see packages/cli/src/utils/nodeShim.ts
// Restores Http2SecureServer#shouldUpgradeCallback, which Node's HTTP/1
// fallback calls for WebSocket upgrades but never defines (Node 22.21.0).
"use strict";
const http2 = require("node:http2");
try {
  const probe = http2.createSecureServer({ allowHTTP1: true });
  const proto = Object.getPrototypeOf(probe);
  if (proto && typeof probe.shouldUpgradeCallback !== "function") {
    Object.defineProperty(proto, "shouldUpgradeCallback", {
      value: function shouldUpgradeCallback() {
        return this.listenerCount("upgrade") > 0;
      },
      writable: true,
      configurable: true,
      enumerable: false,
    });
  }
  probe.close();
} catch {
  // Nothing to patch — leave this Node build alone.
}
`;

/**
 * True when this Node build crashes an allowHTTP1 HTTP/2 server on WebSocket
 * upgrades: the HTTP/1 listener requires `shouldUpgradeCallback` (it exists on
 * plain http servers) while HTTP/2 servers lack it.
 */
export function needsHttp2UpgradeShim(): boolean {
  try {
    const http1 = createServer();
    http1.close();
    if (typeof (http1 as { shouldUpgradeCallback?: unknown }).shouldUpgradeCallback !== "function") {
      return false; // this Node never calls the method
    }
    const http2Server = createSecureServer({ allowHTTP1: true });
    http2Server.close();
    return (
      typeof (http2Server as { shouldUpgradeCallback?: unknown })
        .shouldUpgradeCallback !== "function"
    );
  } catch {
    return false;
  }
}

/** Writes the shim next to the registry (idempotent) and returns its path. */
function ensureShimFile(): string {
  const shimPath = join(REGISTRY_DIR, SHIM_FILENAME);
  try {
    if (existsSync(shimPath) && readFileSync(shimPath, "utf8") === SHIM_SOURCE) {
      return shimPath;
    }
    mkdirSync(REGISTRY_DIR, { recursive: true });
    writeFileSync(shimPath, SHIM_SOURCE, "utf8");
  } catch {
    // Non-fatal: without the shim the proxy simply keeps its upstream bug, and
    // the start command's watchdog restarts it if it dies.
  }
  return shimPath;
}

/**
 * Adds `--require <shim>` to NODE_OPTIONS for the portless proxy daemon, which
 * inherits this environment. Returns the env unchanged on healthy Node builds.
 */
export function withHttp2UpgradeShim(env: NodeJS.ProcessEnv): NodeJS.ProcessEnv {
  if (!needsHttp2UpgradeShim()) return env;
  const shimPath = ensureShimFile();
  if (!existsSync(shimPath)) return env;
  const existing = env.NODE_OPTIONS?.trim();
  if (existing?.includes(SHIM_FILENAME)) return env;
  // Node unescapes backslashes inside quoted NODE_OPTIONS values, which would
  // mangle a Windows path into `C:Usersme...`. Forward slashes are accepted on
  // every platform and survive the quotes that paths with spaces need.
  const flag = `--require "${shimPath.replace(/\\/g, "/")}"`;
  return { ...env, NODE_OPTIONS: existing ? `${existing} ${flag}` : flag };
}
